
def test_imports():
    import api.service
    import models.train
    import features.technical
    import data.fetch
    import backtest.simulate
    import sports.pga.client
    import sports.pga.datagolf_client
    import sports.pga.build_training_dataset
    import sports.pga.feature_engineering
    import sports.pga.ingest
    import sports.pga.ingest_history
    import sports.pga.ingest_profiles
    import sports.pga.train_baseline
    import sports.pga.train_neural_model
    import sports.pga.train_multitask_neural_model
    import sports.pga.train_multitask_torch
    import sports.pga.benchmark_torch_env
    import sports.mlb.client
    import sports.mlb.feature_engineering
    import sports.mlb.roster_features
    import sports.mlb.statcast_enrichment
    import sports.mlb.collect_statcast
    import sports.mlb.build_training_dataset
    import sports.mlb.ingest_history
    import sports.mlb.train_baseline
    import sports.mlb.train_torch
    import sports.basketball.client
    import sports.basketball.feature_engineering
    import sports.basketball.ingest_history
    import sports.basketball.rotation_features
    import sports.basketball.build_training_dataset
    import sports.basketball.train_baseline
    import sports.basketball.torch_model
    import sports.basketball.train_torch
    import sports.football.client
    import sports.football.branding
    import sports.football.feature_engineering
    import sports.football.ingest_history
    import sports.football.build_training_dataset
    import sports.football.train_baseline
    import sports.football.torch_model
    import sports.football.train_torch
    import sports.hockey.branding
    import sports.hockey.client
    import sports.hockey.feature_engineering
    import sports.hockey.ingest_history
    import sports.hockey.build_training_dataset
    import sports.hockey.train_baseline
    import sports.hockey.torch_model
    import sports.hockey.train_torch
    import sports.wta.build_training_dataset
    import sports.wta.feature_engineering
    import sports.wta.ingest
    import sports.wta.train_tournament_ranker_torch
