import Header from '../components/Header';
import Footer from '../components/Footer';

function Methodology() {
  return (
    <>
      <Header />
      <main className="legal-page">
        <article className="legal-content">
          <h1>Model Methodology</h1>
          <p className="legal-updated">Last updated: March 1, 2026</p>
          <p>
            This page explains, at a high level, how SeekingBeta.AI model ratings are produced and how
            performance is measured.
          </p>

          <section>
            <h2>1. What the Models Use</h2>
            <p>
              SeekingBeta.AI models are trained on historical market data and derived indicators. Inputs
              include price/volume history and model features that summarize trend, momentum, and
              volatility behavior over time.
            </p>
          </section>

          <section>
            <h2>2. What the Models Output</h2>
            <p>Each model returns:</p>
            <ul>
              <li>A rating: Bullish, Neutral, or Bearish.</li>
              <li>An upside probability estimate for the selected horizon.</li>
              <li>A high-level driver summary to explain the rating context.</li>
            </ul>
          </section>

          <section>
            <h2>3. Time Horizons</h2>
            <p>
              We run multiple model horizons (for example, short-horizon and swing-horizon variants)
              so users can compare signals across different time windows.
            </p>
          </section>

          <section>
            <h2>4. Track Record and Benchmarking</h2>
            <p>
              We publish model track record metrics and compare results against the S&amp;P 500 (SPY)
              for context. Displayed metrics can include return, hit rate, drawdown, Sharpe ratio,
              and related diagnostics.
            </p>
            <p>
              Track record values are based on defined backtest rules and assumptions and are updated
              as new artifacts are refreshed.
            </p>
          </section>

          <section>
            <h2>5. What This Is Not</h2>
            <p>
              SeekingBeta.AI does not provide personalized investment advice. Ratings are generated by
              automated statistical models and may be wrong.
            </p>
            <p>
              Market conditions change, and past performance does not guarantee future results.
              Always do your own research before making investment decisions.
            </p>
          </section>

          <section>
            <h2>6. Contact</h2>
            <p>
              Questions about methodology can be sent to{' '}
              <a href="mailto:support@seekingbeta.ai">support@seekingbeta.ai</a>.
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}

export default Methodology;
