import { KeyboardEvent, MouseEvent, useEffect, useMemo, useState } from 'react';
import { Prediction, PredictionAttribution, predictions } from '../api/client';

interface PredictionCardProps {
  prediction: Prediction;
  modelName?: string;
  onClick?: (ticker: string) => void;
}

type LstmModelName = 'lstm_5d' | 'lstm_jackpot';

const MODEL_SIGNAL_DISCLAIMER =
  'Model Signal (not investment advice): This rating is generated by an automated statistical model and may be wrong. It is for educational/reference purposes only and is not a recommendation to buy or sell any security.';

function formatSignalLabel(signal?: string | null): string {
  const normalized = (signal || '').toLowerCase();
  if (normalized === 'buy' || normalized === 'strong_buy') return 'Bullish';
  if (normalized === 'sell' || normalized === 'avoid') return 'Bearish';
  return 'Neutral';
}

function formatSignalClass(signal?: string | null): 'buy' | 'sell' | 'hold' {
  const normalized = (signal || '').toLowerCase();
  if (normalized === 'buy' || normalized === 'strong_buy') return 'buy';
  if (normalized === 'sell' || normalized === 'avoid') return 'sell';
  return 'hold';
}

function buildTopDrivers(probability: string, probValue: number, horizon: string): string[] {
  const directionalSummary =
    probValue >= 0.55
      ? 'Recent price action is leaning upward versus recent volatility.'
      : probValue <= 0.45
      ? 'Recent price action is soft, with downside pressure elevated.'
      : 'Recent momentum is mixed with no clear directional edge.';

  return [
    `Upside probability is ${probability}% over the ${horizon} horizon.`,
    directionalSummary,
  ];
}

function prettifyFeatureName(feature: string): string {
  return feature
    .replace(/_/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function friendlyFeatureName(feature: string): string {
  const normalized = feature.toLowerCase().replace(/[^a-z0-9]/g, '');
  const labels: Record<string, string> = {
    bollingerupper: 'Upper Bollinger band',
    bollingerlower: 'Lower Bollinger band',
    yesterdayclose: 'Previous close',
    volume: 'Volume',
    rsi: 'RSI momentum',
    macd: 'MACD momentum',
    numarticles: 'News volume',
  };
  return labels[normalized] ?? prettifyFeatureName(feature);
}

function buildAttributionTopDrivers(
  attribution: PredictionAttribution | null | undefined,
  probValue: number,
  fallback: string[]
): string[] {
  if (!attribution || typeof attribution !== 'object') {
    return fallback;
  }

  const rawDrivers = Array.isArray(attribution.top_drivers)
    ? attribution.top_drivers
    : [];

  const drivers = rawDrivers.filter((d: any) => d && typeof d.feature === 'string').slice(0, 3);
  if (drivers.length === 0) {
    return fallback;
  }

  const positiveCount = drivers.filter(
    (d: any) => String(d.direction || '').toLowerCase() !== 'negative'
  ).length;
  const negativeCount = drivers.length - positiveCount;
  const biasLine =
    positiveCount > negativeCount
      ? 'Short-term model bias: mildly bullish.'
      : negativeCount > positiveCount
      ? 'Short-term model bias: mildly bearish.'
      : probValue >= 0.5
      ? 'Short-term model bias: slightly bullish.'
      : 'Short-term model bias: mixed to neutral.';

  const keyFactors = drivers
    .map((d: any) => friendlyFeatureName(String(d.feature)))
    .filter((name: string, index: number, arr: string[]) => arr.indexOf(name) === index)
    .slice(0, 3);

  return [
    biasLine,
    `Key factors: ${keyFactors.join(', ')}.`,
    'Interpretation is approximate and can change as new data arrives.',
  ];
}

function normalizeLstmModelName(model: string | null | undefined): LstmModelName | null {
  if (model === 'lstm_5d' || model === 'lstm_jackpot') return model;
  return null;
}

function PredictionCard({ prediction, modelName, onClick }: PredictionCardProps) {
  const { ticker, signal, prob_up, last_close, horizon } = prediction as any;
  const [isFlipped, setIsFlipped] = useState(false);
  const [showInfo, setShowInfo] = useState(false);
  const [attribution, setAttribution] = useState<PredictionAttribution | null>(
    prediction.attribution ?? null
  );
  const [attributionLoading, setAttributionLoading] = useState(false);
  const [attributionError, setAttributionError] = useState<string | null>(null);

  const resolvedModelName = useMemo(
    () => normalizeLstmModelName(modelName ?? (prediction as any).model),
    [modelName, prediction]
  );

  useEffect(() => {
    setAttribution(prediction.attribution ?? null);
    setAttributionLoading(false);
    setAttributionError(null);
  }, [prediction]);

  const signalClass = formatSignalClass(signal);
  const signalLabel = formatSignalLabel(signal);
  const probability = prob_up !== null ? (prob_up * 100).toFixed(1) : '0.0';
  const probValue = prob_up ?? 0;
  const probClass = probValue >= 0.55 ? 'high' : probValue >= 0.45 ? 'medium' : 'low';
  const price = last_close?.toFixed(2) || '—';
  const horizonLabel = horizon || '1d';
  const topDrivers = buildAttributionTopDrivers(
    attribution,
    probValue,
    buildTopDrivers(probability, probValue, horizonLabel)
  );

  const handleFlip = () => {
    setIsFlipped((prev) => {
      const next = !prev;
      if (next && !attribution && !attributionLoading && resolvedModelName && ticker) {
        setAttributionLoading(true);
        setAttributionError(null);
        predictions
          .getAttribution(resolvedModelName, ticker, 3)
          .then((response) => {
            if (response?.attribution) {
              setAttribution(response.attribution);
            } else {
              setAttributionError('Attribution details are temporarily unavailable.');
            }
          })
          .catch(() => {
            setAttributionError('Attribution details are temporarily unavailable.');
          })
          .finally(() => {
            setAttributionLoading(false);
          });
      }
      return next;
    });
    setShowInfo(false);
  };

  const handleKeyFlip = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleFlip();
    }
  };

  const handleInfoClick = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    setShowInfo((prev) => !prev);
  };

  const handleOpenCompany = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (onClick) {
      onClick(ticker);
    }
  };

  return (
    <div
      className={`prediction-card${onClick ? ' clickable' : ''}${isFlipped ? ' is-flipped' : ''}`}
      onClick={handleFlip}
      onKeyDown={handleKeyFlip}
      role="button"
      tabIndex={0}
      aria-label={`${ticker} model card. Press to ${isFlipped ? 'show front' : 'show top drivers'}.`}
      aria-pressed={isFlipped}
    >
      <div className="prediction-card-inner">
        <div className="prediction-card-face prediction-card-front">
          <div className="prediction-header">
            <span className="prediction-ticker">{ticker}</span>
            <div className="prediction-signal-stack">
              <div className="prediction-signal-row">
                <span className={`prediction-signal ${signalClass}`}>{signalLabel}</span>
                <button
                  type="button"
                  className="prediction-info-btn"
                  onClick={handleInfoClick}
                  aria-label="More info about model signal"
                  aria-expanded={showInfo}
                >
                  i
                </button>
              </div>
              {showInfo && <div className="prediction-signal-popover">{MODEL_SIGNAL_DISCLAIMER}</div>}
            </div>
          </div>
          <div className="prediction-stats">
            <div className="prediction-stat">
              <span className="prediction-stat-label">Last Price</span>
              <span className="prediction-stat-value">${price}</span>
            </div>
            <div className="prediction-stat">
              <span className="prediction-stat-label">Horizon</span>
              <span className="prediction-stat-value">{horizonLabel}</span>
            </div>
          </div>
          <div className="prediction-probability">
            <div className="prediction-stat">
              <span className="prediction-stat-label">Upside Probability</span>
              <span className="prediction-stat-value">{probability}%</span>
            </div>
            <div className="probability-bar-bg">
              <div className={`probability-bar ${probClass}`} style={{ width: `${probability}%` }} />
            </div>
          </div>

          <div className="prediction-card-actions">
            {onClick && (
              <button
                type="button"
                className="prediction-company-btn"
                onClick={handleOpenCompany}
                aria-label={`Open ${ticker} company profile`}
              >
                Company Profile
              </button>
            )}
            <span className="prediction-flip-hint">Click card to view top drivers</span>
          </div>
        </div>

        <div className="prediction-card-face prediction-card-back">
          <div className="prediction-back-header">
            <span className="prediction-ticker">{ticker}</span>
            <span className="prediction-back-title">Why this signal?</span>
          </div>
          <ul className="prediction-drivers-list">
            {topDrivers.map((driver, index) => (
              <li key={`${ticker}-driver-${index}`}>{driver}</li>
            ))}
          </ul>
          {attributionLoading && (
            <div className="prediction-drivers-loading">Refining factors...</div>
          )}
          {attributionError && (
            <div className="prediction-drivers-loading">Using fallback summary right now.</div>
          )}

          <div className="prediction-card-actions">
            {onClick && (
              <button
                type="button"
                className="prediction-company-btn"
                onClick={handleOpenCompany}
                aria-label={`Open ${ticker} company profile`}
              >
                Company Profile
              </button>
            )}
            <span className="prediction-flip-hint">Click card to return</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PredictionCard;
